# .github/workflows/snake.yml
name: Generate Snake Animation

on:
  schedule:
    # Her gün UTC ile 00:00'da çalışır
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        id: snake_gif
        with:
          github_user_name: kamal1zm  # BURAYI KESİNLİKLE KONTROL ET (Kullanıcı adın)
          outputs: |
            dist/github-snake.svg
            dist/github-snake.gif
            dist/github-snake-dark.svg
            dist/github-snake-dark.gif

      - uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist
